name: Code Formatting Check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' 

      - name: Install dotnet format
        run: dotnet tool install -g dotnet-format

      - name: Restore dependencies
        run: dotnet restore

      - name: Check code formatting
        run: dotnet format --verify-no-changes
